# font_family ComicShannsMono Nerd Font
# font_family Maple Mono NF CN Medium
# font_family Ioskeley Mono
font_family Hack Nerd Font
font_size 12

background_opacity 0.80

# разбиение окон по горизонтали
enabled_layouts horizontal

# Tab bar.
tab_bar_edge bottom
tab_bar_margin_width 5
tab_bar_margin_height 5 0
# tab_bar_style separator
# tab_separator ""

tab_bar_min_tabs 2
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {index} {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# === Custom Tab Colors ===
# tab_bar_background #2e2e2e
#
# active_tab_background #2e2e2e
# active_tab_foreground #1bfd9c
#
# inactive_tab_background #2e2e2e
# inactive_tab_foreground #e1e1e1

# отключаем курсив в названиях вкладок
active_tab_font_style normal
inactive_tab_font_style normal

# specially TBK mini
# Tabs keybinding
# map ctrl+right next_tab
# map ctrl+left previous_tab
# map alt+c close_tab
# map alt+t new_tab

# include tokyonight_moon.conf
# include nord.conf
# include solarized_dark.conf
# include darkvoid.conf
include zen.conf
