font_family ComicShannsMono Nerd Font
font_size 14

background_opacity 0.90

# background #282828

# specially TBK mini
# map alt+w new_window
# map alt+shift+w close_window
# map ctrl+] next_window
# map ctrl+[ previous_window

# active_border_color #46474a

# разбиение окон по горизонтали
enabled_layouts horizontal

# Tab bar.
tab_bar_edge bottom
tab_bar_margin_width 5
tab_bar_margin_height 5 0
tab_bar_style separator
tab_separator ""
tab_bar_min_tabs 2
tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370} ({index}) {tab.active_oldest_exe} {fmt.fg._5c6370}{fmt.bg.default} "

active_tab_title_template "{fmt.fg._BAA0E8}{fmt.bg.default}{fmt.fg.default}{fmt.bg._BAA0E8} ({index}) {tab.active_oldest_exe} {fmt.fg._BAA0E8}{fmt.bg.default} "

# specially TBK mini
# Tabs keybinding
# map ctrl+right next_tab
# map ctrl+left previous_tab
# map alt+c close_tab
# map alt+t new_tab

include gruvbox_theme.conf
