[module/i3]
type = internal/i3
index-sort = true

format = <label-state> <label-mode>
; format-background=${colors.bg}
; format-background=#00000000

label-mode = %mode%
label-mode-padding = 1
; label-mode-background = ${colors.color2}

label-focused = 
; label-focused-foreground = ${colors.foreground}
label-focused-padding = 1

; label-unfocused =  
label-unfocused = %index%
; label-unfocused-font = 1
; label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

label-visible= %icon% 
; label-visible-foreground = ${colors.foreground}
label-visible-padding = 1

label-urgent= 󰀨
; label-urgent-foreground = ${colors.foreground}
label-urgent-padding = 1
