# Backend
# glx (OpenGL) it's more friendly to color inversion or blur background
backend = "glx";

# disable stencil buffer in  openGl backend
glx-no-stencil = true;

# Opacity
# opacity for active windows
active-opacity = 1;

# opacity for inactive windows
inactive-opacity = 1;

# opacity of window tiltebars and borders
frame-opacity = 1;

# let inactive opacity set by -i override values of windows
inactive-opacity-override = false;

opacity-rule = [
	"90:class_g = 'Kitty' && focused",
	"70:class_g = 'Kitty' && 1focused",
];

blur-background = true;

# for example
# blur-background-exclude = [
  # "window_type = 'firefox'"
# ]

blur-method = "dual_kawase";

# min: 0, max 20
blur-strengh = 8;

# Fading
# fade window in/out when opening/closing and when opacity changes
fading = true;

# time between step in fade step, in milliseconds
fade-delta = 4;

# do not fade on window open/close
no-fading-openclose = false;

fade-exclude = [];

# Other settings
mark-wmwin-focused = true;
mark-ovredir-focused = true;
vsync = true;
unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;

# try to detect windows with rounded corners
detect-rounded-corners = true;

# Window type settings
wintypes: {
	# for polybar
  dock = {
	  shadow = false;
	}
};

shadow = false;
corner-radius = 0;
