require("core.keymaps")
require("core.plugins")
require("core.options")

-- plugins
require("plugins.indend_block")
require("plugins.color_theme")
require("plugins.buffer_line")
require("plugins.toggle_term")
require("plugins.live_server")
require("plugins.tree_sitter")
require("plugins.remote_nvim")
require("plugins.ts_autotag")
require("plugins.telescope")
require("plugins.colorizer")
require("plugins.gitsigns")
-- require("plugins.hologram")
require("plugins.comment")
require("plugins.lualine")
require("plugins.conform")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
